# -*- encoding: utf-8 -*-
"""
Flask Web App - Generated by www.AppSeed.us
AppSeed - developed by RoSoft | www.RoSoftware.ro
Licence: MIT
"""

from flask            import Flask
from flask_bootstrap  import Bootstrap
from flask_sqlalchemy import SQLAlchemy
from flask_pymongo    import PyMongo
from flask_login      import LoginManager
from flask_bcrypt     import Bcrypt
from flask_mail       import Mail


# load RES
from .assets import Assets as assets 

app = Flask(__name__, static_url_path='/static')

#Configuration of application, see configuration.py, choose one and uncomment.
#app.config.from_object('app.configuration.ProductionConfig')
app.config.from_object('app.configuration.DevelopmentSqliteConfig')

# Expose globally the assets class
app.add_template_global(assets, 'assets')

bs   = Bootstrap   (app) #flask-bootstrap
db   = SQLAlchemy  (app) #flask-sqlalchemy
lm   = LoginManager(   ) #flask-loginmanager
bc   = Bcrypt      (app) #flask-bcrypt
mail = Mail(app)

lm.init_app(app)


from . import views, models


from flask_admin import Admin
from flask_admin.contrib.sqla import ModelView

admin = Admin(app, name='dashboard', template_mode='bootstrap3')

class UserView(ModelView):
    column_exclude_list = ['password', 'password_q']
    column_search_list = ['user', 'name']

admin.add_view(UserView(models.User, db.session))

